services:
  db:
    image: postgres:11.4-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: docker_test
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  app:
    image: vloddos/web-server
    ports:
      - "3000-3004:3000"
    environment:
      POSTGRES_HOST: db
    restart: always
    links:
      - db
  nginx:
    image: nginx:1.17.2-alpine
    container_name: nginx
    ports:
      - "8989:8989"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app